language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
cache:
  directories:
    - node_modules
  yarn: true
before_script:
  - nvm install 5
  - npm install
  - npm run build
script:
  - ls -al style.css
  - ls -al bundle.js
notifications:
  slack: pulsedesign:bq233WnTbLy5FcUDOMdVyV1f
