language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
cache:
  directories:
  - node_modules
  yarn: true
before_script:
  - npm install -g gulp
script: gulp
  slack: pulsedesign:bq233WnTbLy5FcUDOMdVyV1f
